# Generated by Django 3.0.2 on 2022-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_age', models.IntegerField()),
                ('stu_address', models.CharField(max_length=50)),
                ('stu_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
