# Generated by Django 3.0.2 on 2022-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
