# Generated by Django 3.0.2 on 2022-06-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='tcity',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tmarks',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tname',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tpass_date',
            field=models.DateField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='troll',
            field=models.IntegerField(default=1, null=True, unique=True),
        ),
    ]
