# Generated by Django 3.0.2 on 2022-06-27 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20220627_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tpass_date',
            field=models.DateField(default=datetime.date(2022, 6, 27)),
        ),
    ]
