# Generated by Django 3.0.2 on 2022-03-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=50)),
                ('stu_phone', models.CharField(max_length=20)),
                ('stu_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
