# Generated by Django 3.0.2 on 2022-03-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=255)),
                ('stu_email', models.EmailField(max_length=255)),
                ('stu_age', models.IntegerField()),
                ('stu_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
